### ISSUE TITLE
Provide better documentation

### ISSUE THREAD

**Issue by domkun** [momjs/mom#2]
Documentation lacks details. Especially event handling is not clear.

**Comment by alexan** [comment]
will work on this over the holidays.
basic documentation could be found here:
http://mom.js.org/documentations/modules.html#communication-between-modules

but I will create a separate section addressing communication

**Comment by domkun** [comment]
Splendid.

**Comment by alexan** [comment]
please checkout http://mom.js.org/documentations/eventBus.html and give feedback

**Comment by domkun** [comment]
Cool. Thanks
